# syntax=docker/dockerfile:1

FROM golang:1.17-alpine

RUN mkdir /app
ADD . /app
WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o main .

EXPOSE 8081

CMD ["/app/main"]